server {
  listen 80;
<<<<<<< HEAD
  server_name _;
=======
  server_name localhost;
>>>>>>> 06170f5a5e6b6979cccd2b4ff1fd1ea4a02eb102

  root /usr/share/nginx/html;
  index index.html;

<<<<<<< HEAD
  location /api/ {
    proxy_pass http://backend:3001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

=======
>>>>>>> 06170f5a5e6b6979cccd2b4ff1fd1ea4a02eb102
  location / {
    try_files $uri $uri/ /index.html;
  }
}
<<<<<<< HEAD
=======

>>>>>>> 06170f5a5e6b6979cccd2b4ff1fd1ea4a02eb102
